### PR TITLE
Secp256k1 v0.12.3.x

### PR DESCRIPTION
**Pull request by CaveSpectre11**
Merge Branch into Mainline

### CODE REVIEW

**Comment by CaveSpectre11** [comment]
Addressing https://github.com/ida-pay/idapay-refresh/issues/4

**Comment by CaveSpectre11** [comment]
I'm inclined to close and hold off on this one given what Darkkill shared:

"apt-get install build-essential libtool autoconf-archive autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils"

**Comment by sub307** [comment]
Haven't followed the intell on this one, so can't give a decent review here.

**Review by sub307 — APPROVED** [review]

**Review by Altcoin-Cash — APPROVED** [review]
Compiled on ubuntu 16x and 18x

**Pull request merged**
