### PR TITLE
fix

### PR DESCRIPTION
**Pull request by kido72**
Delete unused theme IDAPAY-light-hires

### CODE REVIEW

**Comment by CaveSpectre11** [comment]
Initially NACK.  Subject of the PR needs to be more clear; but moreso there needs way more details into why you're doing this.  What makes this theme unused and the other's are used?

**Comment by kido72** [comment]
So, this theme not have it forlder with pictures and icons (IDAPAY-light-hires)
idapay-refresh/src/qt/res/images# ls
crownium  drkblue  light  trad
No folder light-hires

**Comment by CaveSpectre11** [comment]
Every reference I see in light-hires.css references images in /images/light/

**Comment by kido72** [comment]
But it not used icons and repeat light theme. See windows wallet.

**Comment by kido72** [comment]
I think someone wanted to create their own theme and did not finish the work. Why have almost the same styles in the duplicate theme?

**Comment by CaveSpectre11** [comment]
I'm not convinced it's not functional; so I am going to go ahead and close this as rejected.  If we want to revisit it, we can; but there will still be more things that need to change to completely remove it (e.g. the css file, etc)

**Pull request closed without merging**
